SELECT NOW();

SELECT NOW() AS DATA_E_HORA;

SELECT NOW() FROM dual; --> O Oracle Database não aceita apenas o chamento da função, é necessário, portanto, realizar o from "dual".

-->Tipo flutuante: "NUMERIC(5,2)", OU SEJA, O NÚMERO TERÁ, AO TOTAL, 5 CASAS E 2 CASAS APÓS A VÍRGULA.

/*
Versão da tabela "PESSOA" não normalizada:

CREATE TABLE PESSOA (
	NOME VARCHAR(40),
	GENERO CHAR(1) CHECK (GENERO='M' OR GENERO='F'),
	DT_NASCIM DATE,
	ENDERECO VARCHAR(100),
	COMIDAS_FAVORITAS VARCHAR(200)
);

*/

-->Versão normalizada da tabela "PESSOA":

CREATE TABLE PESSOA (
	ID_PESSOA INT,
	NOME VARCHAR(20),
	SOBRENOME VARCHAR(20),
	GENERO CHAR(1) CHECK (GENERO='M' OR GENERO='F'),
	DT_NASCIM DATE,
	RUA VARCHAR(30),
	CIDADE VARCHAR(20),
	ESTADO VARCHAR(20),
	PAIS VARCHAR(20),
	CODIGO_POSTAL VARCHAR(20),
	CONSTRAINT PK_PESSOA PRIMARY KEY (ID_PESSOA)
);

SELECT * FROM PESSOA;

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PESSOA'; --> Lista as informações de cada coluna da tabela.

--> Criando tabela "COMIDA_FAVORITA" que se conectará com a tabela "PESSOA" através de uma FOREIGN KEY.

CREATE TABLE COMIDA_FAVORITA (
	ID_PESSOA SERIAL,
	COMIDA VARCHAR(20),
	CONSTRAINT PK_COMIDA_FAVORITA PRIMARY KEY (ID_PESSOA, COMIDA),
	CONSTRAINT FK_COMIDA_FAVORITA_ID_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID_PESSOA)
);

SELECT * FROM COMIDA_FAVORITA;

INSERT INTO PESSOA (ID_PESSOA, NOME, SOBRENOME, GENERO, DT_NASCIM, RUA, CIDADE, ESTADO, PAIS, CODIGO_POSTAL)
					VALUES	(1, 'Huandel', 'Siqueira', 'M', '2001-08-01', 'Prof. Felisberto', 'Pelotas', 'Rio Grande do Sul', 'Brasil', '96045160'),
						  	(2, 'William', 'Turner', 'M', '1972-05-27', NULL, NULL, NULL, NULL, NULL);
						   
SELECT * FROM PESSOA;

INSERT INTO COMIDA_FAVORITA (ID_PESSOA, COMIDA)
							VALUES 	(1, 'Cachorro quente'),
									(1, 'Churrasco'),
									(2, 'Pizza');
									
SELECT * FROM COMIDA_FAVORITA;

SELECT COMIDA
FROM COMIDA_FAVORITA
WHERE ID_PESSOA = 1
ORDER BY COMIDA;

INSERT INTO PESSOA (ID_PESSOA, NOME, SOBRENOME, GENERO, DT_NASCIM, RUA, CIDADE, ESTADO, PAIS, CODIGO_POSTAL)
			VALUES	(3, 'Susan', 'Smith', 'F', '1975-11-02', '23 Maple St.', 'Arlington', 'VA', 'USA', '20220');
			
SELECT * FROM PESSOA;

--> Comando de atualização de dados dentro de uma tabela:

UPDATE PESSOA 
SET RUA = '1225 Tremont St.',
	CIDADE = 'Boston',
	ESTADO = 'MA',
	PAIS = 'USA',
	CODIGO_POSTAL = '02138'
WHERE ID_PESSOA = 2;

SELECT * 
FROM PESSOA 
ORDER BY ID_PESSOA;

--> Importante ao inserir dados. Formato: 'AAAA-MM-DD'

SELECT NOME, SOBRENOME, GENERO
FROM PESSOA
WHERE NOME = 'Huandel';

SELECT NOME, SOBRENOME, GENERO
FROM PESSOA
WHERE GENERO = 'M';

SELECT P.NOME, P.SOBRENOME, P.GENERO, C.COMIDA
FROM PESSOA P
INNER JOIN COMIDA_FAVORITA C
ON P.ID_PESSOA = C.ID_PESSOA;

