SELECT NOW();

SELECT NOW() AS DATA_E_HORA;

SELECT NOW() FROM dual; --> O Oracle Database não aceita apenas o chamento da função, é necessário, portanto, realizar o from "dual".

-->Tipo flutuante: "NUMERIC(5,2)", OU SEJA, O NÚMERO TERÁ, AO TOTAL, 5 CASAS E 2 CASAS APÓS A VÍRGULA.

/*
Versão da tabela "PESSOA" não normalizada:

CREATE TABLE PESSOA (
	NOME VARCHAR(40),
	GENERO CHAR(1) CHECK (GENERO='M' OR GENERO='F'),
	DT_NASCIM DATE,
	ENDERECO VARCHAR(100),
	COMIDAS_FAVORITAS VARCHAR(200)
);

*/

-->Versão normalizada da tabela "PESSOA":

CREATE TABLE PESSOA (
	ID_PESSOA INT,
	NOME VARCHAR(20),
	SOBRENOME VARCHAR(20),
	GENERO CHAR(1) CHECK (GENERO='M' OR GENERO='F'),
	DT_NASCIM DATE,
	RUA VARCHAR(30),
	CIDADE VARCHAR(20),
	ESTADO VARCHAR(20),
	PAIS VARCHAR(20),
	CODIGO_POSTAL VARCHAR(20),
	CONSTRAINT PK_PESSOA PRIMARY KEY (ID_PESSOA)
);

SELECT * FROM PESSOA;

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PESSOA'; --> Lista as informações de cada coluna da tabela.

--> Criando tabela "COMIDA_FAVORITA" que se conectará com a tabela "PESSOA" através de uma FOREIGN KEY.

CREATE TABLE COMIDA_FAVORITA (
	ID_PESSOA SERIAL,
	COMIDA VARCHAR(20),
	CONSTRAINT PK_COMIDA_FAVORITA PRIMARY KEY (ID_PESSOA, COMIDA),
	CONSTRAINT FK_COMIDA_FAVORITA_ID_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID_PESSOA)
);

SELECT * FROM COMIDA_FAVORITA;

INSERT INTO PESSOA (ID_PESSOA, NOME, SOBRENOME, GENERO, DT_NASCIM, RUA, CIDADE, ESTADO, PAIS, CODIGO_POSTAL)
					VALUES (1, 'Huandel', 'Siqueira', 'M', '2001-08-01', 'Prof. Felisberto', 'Pelotas', 'Rio Grande do Sul', 'Brasil', '96045160'),
						   (2, 'William', 'Turner', 'M', '1972-05-27', NULL, NULL, NULL, NULL, NULL);
						   
SELECT * FROM PESSOA;

