CREATE TABLE ALUNO (
	MATRICULA_ALUNO INT PRIMARY KEY,
	NATURALIDADE VARCHAR(15),
	FILIACAO VARCHAR(70),
	ESTADO_CIVIL VARCHAR(15),
	NR_RG INT UNIQUE NOT NULL,
	DATA_EXPEDICAO_RG DATE NOT NULL,
	NOME_ALUNO VARCHAR(70) NOT NULL,
	FOTO TXID_SNAPSHOT,
	RUA_END VARCHAR(50) NOT NULL,
	COMPLEMENTO_END VARCHAR(25),
	BAIRRO_END VARCHAR(25) NOT NULL,
	CEP_END INT NOT NULL,
	NOME_RESPONSAVEL VARCHAR(70) NOT NULL,
	EMAIL_ALUNO VARCHAR(50) NOT NULL,
	/*FOREIGN KEY (TELEFONE_FK) REFERENCES TELEFONE (TELEFONE_PK),*/
	GRAU_PARENTESCO_RESPONSAVEL VARCHAR(15) NOT NULL,
	NACIONALIDADE VARCHAR(20), 
	DATA_NASCIMENTO DATE NOT NULL,
	TELEFONE_RESPONSAVEL VARCHAR(15) NOT NULL
	/*FOREIGN KEY (COD_CURSO_FK) REFERENCES CURSO (COD_CURSO)*/
);

CREATE TABLE TELEFONE (
	TELEFONE_PK INT PRIMARY KEY,
	TELEFONE_RES VARCHAR(15),
	TELEFONE_CEL VARCHAR(15) NOT NULL,
	FOREIGN KEY (TELEFONE_PK) REFERENCES ALUNO (MATRICULA_ALUNO)
);

CREATE TABLE CURSO (
	COD_CURSO INT PRIMARY KEY,
	NOME_CURSO VARCHAR(40) NOT NULL,
	DURACAO VARCHAR(15) NOT NULL,
	TURNO CHAR(1) NOT NULL,
	DATA_CRIACAO DATE NOT NULL,
	FOREIGN KEY (COD_CURSO) REFERENCES ALUNO (MATRICULA_ALUNO)
);

CREATE TABLE PROFESSOR_DISCIPLINA (
	ID_PROFESSOR_DISCIPLINA INT PRIMARY KEY,
	CURSO_MINISTRADO VARCHAR(30) NOT NULL,
	GRAU_INSTRUCAO VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO_PROF DATE NOT NULL,
	TEL_RECADO VARCHAR(15),
	RUA_END VARCHAR(40) NOT NULL,
	COMPLEMENTO_END VARCHAR(25),
	CEP_END VARCHAR(8) NOT NULL,
	CIDADE_END VARCHAR(25) NOT NULL,
	BAIRRO_END VARCHAR(20) NOT NULL,
	ESTADO_CIVIL VARCHAR(15),
	NOME_PROFESSOR VARCHAR(40) NOT NULL,
	TEL_RES VARCHAR(15),
	FILHOS INT,
	NACIONALIDADE VARCHAR(20) NOT NULL,
	VALE_TRANSPORTE CHAR(3) NOT NULL,
	FOTO TXID_SNAPSHOT,
	SALARIO NUMERIC(7,2),
	DATA_ADMISSAO_PROF DATE NOT NULL,
	CARGA_HORARIA INT NOT NULL,
	TEL_CEL VARCHAR(15) NOT NULL,
	ORGAO_EMISSOR_RG VARCHAR(30) NOT NULL,
	NR_RG VARCHAR(15) NOT NULL,
	DATA_EXPEDICAO_RG DATE NOT NULL,
	NOME_PAI VARCHAR(50),
	NOME_MAE VARCHAR(50),
	FOREIGN KEY (ID_PROFESSOR_DISCIPLINA) REFERENCES CURSO (COD_CURSO),
	COD_CURSO INT NOT NULL,
	NOME_DISCIPLINA VARCHAR(30) NOT NULL,
	EMENTA VARCHAR(300) NOT NULL
);

CREATE TABLE ALUNO_POSSUI_MATRICULA_CURSO_ALUNO_PROFESSOR_DISCIPLINA (
	COD_POSSUI_MAT INT PRIMARY KEY,
	FOREIGN KEY (COD_POSSUI_MAT) REFERENCES ALUNO (MATRICULA_ALUNO),
	FOREIGN KEY (COD_POSSUI_MAT) REFERENCES CURSO (COD_CURSO),
	FOREIGN KEY (COD_POSSUI_MAT) REFERENCES PROFESSOR_DISCIPLINA (ID_PROFESSOR_DISCIPLINA)
);

CREATE TABLE CURSO_DISCIPLINA (
	COD_CURSO_DISCIPLINA INT PRIMARY KEY,
	FOREIGN KEY (COD_CURSO_DISCIPLINA) REFERENCES CURSO (COD_CURSO),
	FOREIGN KEY (COD_CURSO_DISCIPLINA) REFERENCES PROFESSOR_DISCIPLINA (ID_PROFESSOR_DISCIPLINA)
);

CREATE TABLE PRE_REQUISITO (
	ID_PRE_REQUISITO INT PRIMARY KEY,
	FOREIGN KEY (ID_PRE_REQUISITO) REFERENCES PROFESSOR_DISCIPLINA (ID_PROFESSOR_DISCIPLINA)
);