CREATE TABLE TELEFONE (
	TELEFONE_PK INT PRIMARY KEY,
	TELEFONE_RES VARCHAR(15),
	TELEFONE_CEL VARCHAR(15) NOT NULL
	FOREIGN KEY (TELEFONE_FK) REFERENCES ALUNO (MATRICULA_ALUNO),
);

CREATE TABLE ALUNO (
	MATRICULA_ALUNO INT PRIMARY KEY,
	NATURALIDADE VARCHAR(15),
	FILIACAO VARCHAR(70),
	ESTADO_CIVIL VARCHAR(15),
	NR_RG INT UNIQUE NOT NULL,
	DATA_EXPEDICAO_RG DATE NOT NULL,
	NOME_ALUNO VARCHAR(70) NOT NULL,
	FOTO TXID_SNAPSHOT,
	RUA_END VARCHAR(50) NOT NULL,
	COMPLEMENTO_END VARCHAR(25),
	BAIRRO_END VARCHAR(25) NOT NULL,
	CEP_END INT NOT NULL,
	NOME_RESPONSAVEL VARCHAR(70) NOT NULL,
	EMAIL_ALUNO VARCHAR(50) NOT NULL,
	FOREIGN KEY (TELEFONE_FK) REFERENCES TELEFONE (TELEFONE_PK),
	GRAU_PARENTESCO_RESPONSAVEL VARCHAR(15) NOT NULL,
	NACIONALIDADE VARCHAR(20), 
	DATA_NASCIMENTO DATE NOT NULL,
	TELEFONE_RESPONSAVEL VARCHAR(15) NOT NULL,
	FOREIGN KEY (COD_CURSO_FK) REFERENCES CURSO (COD_CURSO)
);